version: '3.8'

services:
  sig-provider:
    platform: linux/x86_64
    image: ghcr.io/blockscout/sig-provider:${SIG_PROVIDER_DOCKER_TAG:-main}
    pull_policy: always
    restart: always
    ports:
      - 8151:8050
