version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    command: postgres -c 'max_connections=3200'
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - "./postgres-data:/var/lib/postgresql/data:rw"
    ports:
      - 58432:5432